### ISSUE TITLE
Minor Update: Make Prev/Next Buttons Compatible with mobile

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#322]
Get rid of the Previous/Next text for smaller/mobile screens. Just get rid of the text, not the buttons themselves, or the arrow icons.
<img width="375" alt="image" src="https://github.com/uclaacm/parcel-pointers/assets/78634083/9b8ba6cf-e7d1-4eb5-ad66-2c98faf5d321">
You can look at things on mobile screens through the instructions in this ticket https://github.com/uclaacm/parcel-pointers/issues/300.

**Comment by lawtlee** [comment]
@Dankco The issue is that the navbuttons are related to the viewport size and since the rest of the page isn't adapted to mobile it won't adapt the navbuttons as well. Once we fix the other css the navbuttons should be fine. Basically there isn't anything wrong with the css for the buttons its just the other elements are stretching it causing the buttons to be stretched too.

**Comment by Dankco** [comment]
Yeah, that is another issue to resolve. I will ticket that. For now let's just remove the Previous/Next text, since the buttons don't really fit well on a mobile screen with them, eg:
![image](https://github.com/uclaacm/parcel-pointers/assets/78634083/bd7b22a4-e0f6-4053-b077-cbb16bf7268a)
